### ISSUE TITLE
Building this project with go build runs into issues

### ISSUE THREAD

**Issue by SanketDG** [Trendyol/docker-shell#12]
Output 

```
../../go/src/docker.io/go-docker/service_create.go:128:36: cannot use dgst (type "github.com/opencontainers/go-digest".Digest) as type "github.com/docker/distribution/vendor/github.com/opencontainers/go-digest".Digest in argument to reference.WithDigest
```

**Comment by mstrYoda** [comment]
What is your OS? Can you tell your go version and also do you already have go-docker in your go packages?

I tried go get docker-shell in a clean linux environment (docker golang to be precise) and it worked well.

**Comment by SanketDG** [comment]
> What is your OS?

Fedora

> Can you tell your go version and also do you already have go-docker in your go packages?

1.10.8, No.

I too tried on a fresh install of go.

**Comment by SanketDG** [comment]
This builds now, thanks!
