### ISSUE TITLE
Crashes if typing run

### ISSUE THREAD

**Issue by ovitente** [Trendyol/docker-shell#19]
**Describe the bug**
Crashes if typing `run`. Even without Enter after it.

**To Reproduce**
1. start app
2. start typing `run` and press space
3. it crashes.

**Expected behavior**
To show available images to run

**Screenshots**
![image](https://user-images.githubusercontent.com/10868371/78987546-fcec0c80-7b36-11ea-9a65-760a4c33c1db.png)

**Text log***
```
det@B-503:~  ds
>>> docker runpanic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.imagesSuggestion(0x14743e0, 0xc0005b4000, 0x14f4ae5)
        /Users/det/Downloads/docker-shell/main.go:229 +0x320
main.completer(0xc0005a2004, 0x4, 0x4, 0x400, 0x0, 0x0)
        /Users/det/Downloads/docker-shell/main.go:166 +0x1d0
github.com/c-bata/go-prompt.(*CompletionManager).Update(...)
        /Users/det/.go/pkg/mod/github.com/c-bata/go-prompt@v0.2.3/completion.go:69
github.com/c-bata/go-prompt.(*Prompt).Input(0xc00007e000, 0x0, 0x0)
        /Users/det/.go/pkg/mod/github.com/c-bata/go-prompt@v0.2.3/prompt.go:260 +0x47e
github.com/c-bata/go-prompt.Input(0x14f6168, 0xb, 0x15166e0, 0xc0001dff50, 0x4, 0x4, 0x5, 0x0)
        /Users/det/.go/pkg/mod/github.com/c-bata/go-prompt@v0.2.3/shortcut.go:16 +0xd8
main.main()
        /Users/det/Downloads/docker-shell/main.go:247 +0x299
```

**Version**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by mstrYoda** [comment]
Hi @ovitente thank you for reporting an issue. I could not reproduce that issue event if I cut internet connection. Do you still facing with it?

How did you install via go get or brew?

**Comment by ovitente** [comment]
Hi @mstrYoda 
1. Installed via git clone + go build
2. Just checked current local build where I've had this issue, and **can not reproduce it now**.
Cloned this repo again into the new dir, compiled, and everything is fine. Hmm
Unfortunately I haven't noticed when it was fixed.

**Possible fix**
* Restart docker service in mac
* Reboot computer

_btw: thank you for this tool, it simplifies my daily work)_

**Comment by mstrYoda** [comment]
> Hi @mstrYoda
> 
> 1. Installed via git clone + go build
> 2. Just checked current local build where I've had this issue, and **can not reproduce it now**.
>    Cloned this repo again into the new dir, compiled, and everything is fine. Hmm
>    Unfortunately I haven't noticed when it was fixed.
> 
> **Possible fix**
> 
> * Restart docker service in mac
> * Reboot computer
> 
> _btw: thank you for this took, it simplifies my daily work)_

Thank you for your time. I'm glad it helps you :)
